# Welcome to Serverless!
#
# This file is the main config file for your service.
#
# Happy Coding!

service: auth
frameworkVersion: '3'

custom:
  common: ${file(../../serverless.common.yml)}

package:
  individually: true

plugins:
  - serverless-offline
  - serverless-offline-lambda-invoke
  - serverless-iam-roles-per-function
  - serverless-plugin-tracing
  - serverless-bundle

provider:
  name: aws
  runtime: nodejs14.x
  stage: ${self:custom.common.serverlessConfiguration.stage}
  region: ${self:custom.common.serverlessConfiguration.region}
  environment: ${self:custom.common.serverlessConfiguration.environment}
  tracing:
    apiGateway: true
    lambda: true
  iamRoleStatements:
    - Effect: Allow
      Action:
        - xray:PutTraceSegments
        - xray:PutTelemetryRecords
      Resource: "*"
functions:
  authorizerFunc:
    handler: authPolicy/generatePolicy.main
    timeout: 30
    cors: true
    events:
      - http:
        integration: lambda
    iamRoleStatements:
      - Effect: "Allow"
        Action:
          - "lambda:InvokeFunction"
        Resource: "*"
  getRole:
    handler: apis/getRoleForUser.getRoleForUser
    events: 
      - http:
          method: GET
          path: auth/role/{email}
          authorizer: authorizerFunc
          cors: true
          integration: lambda
          response:
            headers:
              Access-Control-Allow-Origin: "'*'"
    iamRoleStatements:
      - Effect: "Allow"
        Action:
          - "lambda:InvokeFunction"
        Resource: "*" 
  verifyMSALToken:
    handler: apis/verifyLogin.verifyLogin
    events: 
      - http:
          method: POST
          path: auth/verifyLogin
          response:
            headers:
              Access-Control-Allow-Origin: "'*'"
          cors: true
          integration: lambda