# Welcome to Serverless!
#
# This file is the main config file for your service.
#
# Happy Coding!

service: core
frameworkVersion: '3'

custom:
  common: ${file(../../serverless.common.yml)}

package:
  individually: true

plugins:
  - serverless-offline
  - serverless-offline-lambda-invoke
  - serverless-iam-roles-per-function
  - serverless-plugin-tracing
  - serverless-bundle

provider:
  name: aws
  runtime: nodejs14.x
  stage: ${self:custom.common.serverlessConfiguration.stage}
  region: ${self:custom.common.serverlessConfiguration.region}
  environment: ${self:custom.common.serverlessConfiguration.environment}
  tracing:
    apiGateway: true
    lambda: true
  iamRoleStatements:
    - Effect: Allow
      Action:
        - xray:PutTraceSegments
        - xray:PutTelemetryRecords
      Resource: "*"
functions:
  authorizerFunc:
    handler: auth/generatePolicy.main
    timeout: 30
    cors: true
    events:
      - http:
        integration: lambda
    iamRoleStatements:
      - Effect: "Allow"
        Action:
          - "lambda:InvokeFunction"
        Resource: "*"
  syncEmpMasterWithMIS:
    handler: apis/emp/syncEmpMasterWithMIS.syncEmpMasterWithMIS
    events: 
      - http:
          method: GET
          path: core/emp/sync
          authorizer: authorizerFunc
          cors: true
          integration: lambda
          response:
            headers:
              Access-Control-Allow-Origin: "'*'"
    iamRoleStatements:
      - Effect: "Allow"
        Action:
          - "lambda:InvokeFunction"
        Resource: "*"
  fetchAllEmployeesMaster:
    handler: apis/emp/fetchAllEmployeesMaster.fetchAllEmployeesMaster
    events: 
      - http:
          method: GET
          path: core/emp/fetch
          authorizer: authorizerFunc
          cors: true
          integration: lambda
          response:
            headers:
              Access-Control-Allow-Origin: "'*'"
    iamRoleStatements:
      - Effect: "Allow"
        Action:
          - "lambda:InvokeFunction"
        Resource: "*"
  exportExcelEmpMaster:
    handler: apis/emp/exportExcelEmpMaster.exportExcelEmpMaster
    events: 
      - http:
          method: GET
          path: core/emp/export
          authorizer: authorizerFunc
          cors: true
          integration: lambda
          response:
            headers:
              Access-Control-Allow-Origin: "'*'"
    iamRoleStatements:
      - Effect: "Allow"
        Action:
          - "lambda:InvokeFunction"
        Resource: "*"
  createOrUpdateTeam:
    handler: apis/team/createOrUpdateTeam.createOrUpdateTeam
    events: 
      - http:
          method: PUT
          path: core/team/createOrUpdate
          authorizer: authorizerFunc
          cors: true
          integration: lambda
          response:
            headers:
              Access-Control-Allow-Origin: "'*'"
    iamRoleStatements:
      - Effect: "Allow"
        Action:
          - "lambda:InvokeFunction"
        Resource: "*"
  fetchAllTeams:
    handler: apis/team/fetchAllTeams.fetchAllTeams
    events: 
      - http:
          method: GET
          path: core/team/fetch
          authorizer: authorizerFunc
          cors: true
          integration: lambda
          response:
            headers:
              Access-Control-Allow-Origin: "'*'"
    iamRoleStatements:
      - Effect: "Allow"
        Action:
          - "lambda:InvokeFunction"
        Resource: "*"
  deleteTeam:
    handler: apis/team/deleteTeam.deleteTeam
    events: 
      - http:
          method: GET
          path: core/team/delete/{id}
          authorizer: authorizerFunc
          cors: true
          integration: lambda
          response:
            headers:
              Access-Control-Allow-Origin: "'*'"
    iamRoleStatements:
      - Effect: "Allow"
        Action:
          - "lambda:InvokeFunction"
        Resource: "*"
  exportExcelTeamMaster:
    handler: apis/team/exportExcelTeamMaster.exportExcelTeamMaster
    events: 
      - http:
          method: GET
          path: core/team/export
          authorizer: authorizerFunc
          cors: true
          integration: lambda
          response:
            headers:
              Access-Control-Allow-Origin: "'*'"
    iamRoleStatements:
      - Effect: "Allow"
        Action:
          - "lambda:InvokeFunction"
        Resource: "*"
  createOrUpdateProject:
    handler: apis/project/createOrUpdateProject.createOrUpdateProject
    events: 
      - http:
          method: PUT
          path: core/project/createOrUpdate
          authorizer: authorizerFunc
          cors: true
          integration: lambda
          response:
            headers:
              Access-Control-Allow-Origin: "'*'"
    iamRoleStatements:
      - Effect: "Allow"
        Action:
          - "lambda:InvokeFunction"
        Resource: "*"
  fetchAllProjects:
    handler: apis/project/fetchAllProjects.fetchAllProjects
    events: 
      - http:
          method: GET
          path: core/project/fetch
          authorizer: authorizerFunc
          cors: true
          integration: lambda
          response:
            headers:
              Access-Control-Allow-Origin: "'*'"
    iamRoleStatements:
      - Effect: "Allow"
        Action:
          - "lambda:InvokeFunction"
        Resource: "*"
  deleteProject:
    handler: apis/project/deleteProject.deleteProject
    events: 
      - http:
          method: GET
          path: core/project/delete/{id}
          authorizer: authorizerFunc
          cors: true
          integration: lambda
          response:
            headers:
              Access-Control-Allow-Origin: "'*'"
    iamRoleStatements:
      - Effect: "Allow"
        Action:
          - "lambda:InvokeFunction"
        Resource: "*"
  exportExcelProjectMaster:
    handler: apis/project/exportExcelProjectMaster.exportExcelProjectMaster
    events: 
      - http:
          method: GET
          path: core/project/export
          authorizer: authorizerFunc
          cors: true
          integration: lambda
          response:
            headers:
              Access-Control-Allow-Origin: "'*'"
    iamRoleStatements:
      - Effect: "Allow"
        Action:
          - "lambda:InvokeFunction"
        Resource: "*"
  createOrUpdateView:
    handler: apis/view/createOrUpdateView.createOrUpdateView
    events: 
      - http:
          method: PUT
          path: core/view/createOrUpdate
          authorizer: authorizerFunc
          cors: true
          integration: lambda
          response:
            headers:
              Access-Control-Allow-Origin: "'*'"
    iamRoleStatements:
      - Effect: "Allow"
        Action:
          - "lambda:InvokeFunction"
        Resource: "*"
  fetchAllViews:
    handler: apis/view/fetchAllViews.fetchAllViews
    events: 
      - http:
          method: GET
          path: core/view/fetch
          authorizer: authorizerFunc
          cors: true
          integration: lambda
          response:
            headers:
              Access-Control-Allow-Origin: "'*'"
    iamRoleStatements:
      - Effect: "Allow"
        Action:
          - "lambda:InvokeFunction"
        Resource: "*"
  deleteView:
    handler: apis/view/deleteView.deleteView
    events: 
      - http:
          method: GET
          path: core/view/delete/{id}
          authorizer: authorizerFunc
          cors: true
          integration: lambda
          response:
            headers:
              Access-Control-Allow-Origin: "'*'"
    iamRoleStatements:
      - Effect: "Allow"
        Action:
          - "lambda:InvokeFunction"
        Resource: "*"
  createOrUpdateMapping:
    handler: apis/mapping/createOrUpdateMapping.createOrUpdateMapping
    events: 
      - http:
          method: PUT
          path: core/mapping/createOrUpdate
          authorizer: authorizerFunc
          cors: true
          integration: lambda
          response:
            headers:
              Access-Control-Allow-Origin: "'*'"
    iamRoleStatements:
      - Effect: "Allow"
        Action:
          - "lambda:InvokeFunction"
        Resource: "*"
  fetchAllMappings:
    handler: apis/mapping/fetchAllMappings.fetchAllMappings
    events: 
      - http:
          method: GET
          path: core/mapping/fetch
          authorizer: authorizerFunc
          cors: true
          integration: lambda
          response:
            headers:
              Access-Control-Allow-Origin: "'*'"
    iamRoleStatements:
      - Effect: "Allow"
        Action:
          - "lambda:InvokeFunction"
        Resource: "*"
  deleteMapping:
    handler: apis/mapping/deleteMapping.deleteMapping
    events: 
      - http:
          method: GET
          path: core/mapping/delete/{email}
          authorizer: authorizerFunc
          cors: true
          integration: lambda
          response:
            headers:
              Access-Control-Allow-Origin: "'*'"
    iamRoleStatements:
      - Effect: "Allow"
        Action:
          - "lambda:InvokeFunction"
        Resource: "*"
  createOrUpdateRole:
    handler: apis/role/createOrUpdateRole.createOrUpdateRole
    events: 
      - http:
          method: PUT
          path: core/role/createOrUpdate
          authorizer: authorizerFunc
          cors: true
          integration: lambda
          response:
            headers:
              Access-Control-Allow-Origin: "'*'"
    iamRoleStatements:
      - Effect: "Allow"
        Action:
          - "lambda:InvokeFunction"
        Resource: "*"
  fetchAllRoles:
    handler: apis/role/fetchAllRoles.fetchAllRoles
    events: 
      - http:
          method: GET
          path: core/role/fetch
          authorizer: authorizerFunc
          cors: true
          integration: lambda
          response:
            headers:
              Access-Control-Allow-Origin: "'*'"
    iamRoleStatements:
      - Effect: "Allow"
        Action:
          - "lambda:InvokeFunction"
        Resource: "*"
  deleteRole:
    handler: apis/role/deleteRole.deleteRole
    events: 
      - http:
          method: GET
          path: core/role/delete/{id}
          authorizer: authorizerFunc
          cors: true
          integration: lambda
          response:
            headers:
              Access-Control-Allow-Origin: "'*'"
    iamRoleStatements:
      - Effect: "Allow"
        Action:
          - "lambda:InvokeFunction"
        Resource: "*"